name: "Continuous Integration"
on:
  schedule:
    - cron: '0 2 * * *' # 2am UTC
  push:
    branches:
      - master
      - release/*
  create:
  pull_request:
    branches:
      - master

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Commitsar check
        uses: docker://aevea/commitsar

  build-otel-base-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfiles:
          - ngx_otel_module/Dockerfile.base.alpine
          - ngx_otel_module/Dockerfile.base.debian

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Build OTEL NGINX Base Image
        shell: bash
        env:
          DOCKER_BUILDKIT: '1'
        run: ./build.sh 'base' ${{ matrix.dockerfiles }}
      - name: Push to Container Registry
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin && \
            ./push.sh "ghcr.io/nginxinc/"

  build-brotli-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nginx-version: [ 1.19.10, 1.20.1, 1.21.6, 1.23.3 ]
        dockerfiles:
          - ngx_http_brotli_filter_module/Dockerfile.alpine
          - ngx_http_brotli_filter_module/Dockerfile.debian

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Cache downloads
        uses: actions/cache@v2
        with:
          key: downloads-${{ hashFiles('nginx_build_versions.txt') }}
          path: downloads
      - name: Build Container Images
        shell: bash
        env:
          DOCKER_BUILDKIT: '1'
        run: ./build.sh ${{ matrix.nginx-version }} ${{ matrix.dockerfiles }}
      - name: Push to Container Registry
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin && \
            ./push.sh "ghcr.io/nginxinc/"

  build-otel-image:
    needs: build-otel-base-image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nginx-version: [ 1.19.10, 1.20.1, 1.21.6, 1.23.3 ]
        dockerfiles:
          - ngx_otel_module/Dockerfile.alpine
          - ngx_otel_module/Dockerfile.debian

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Cache downloads
        uses: actions/cache@v2
        with:
          key: downloads-${{ hashFiles('nginx_build_versions.txt') }}
          path: downloads
      - name: Build Container Images
        shell: bash
        env:
          DOCKER_BUILDKIT: '1'
        run: ./build.sh ${{ matrix.nginx-version }} ${{ matrix.dockerfiles }}
      - name: Push to Container Registry
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin && \
            ./push.sh "ghcr.io/nginxinc/"
